version: "3"
services:
  server:
    image: rest-api.jar
    ports:
      - "8083:8082"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/myHiber?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=abcd
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.5
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=abcd
    ports:
      - 3306:3306


networks:
  springmysql-net: